language: php

php:
  - '7.2'
  - '7.3'

cache:
  directories:
    - vendor

install: composer install

script:
  - vendor/bin/phpstan analyse --level 7 src
  - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
